In [1]:
#import dependencies
import pandas as pd
import sqlite3

In [2]:
#create a sqlite3 file
db_name = "opioid_analysis.sqlite"

conn = sqlite3.connect(db_name)
cursor = conn.cursor()

In [5]:
#read our cleaned data csv
df = pd.read_csv("CT_OpioidData_Final.csv")
df.head()

,IncidentID,DateReported,Sex,Race,Age,InjuryPlace,InjuryCity,InjuryCounty,InjuryState,InjuryZip,...,Hydrocodone,Benzodiazepines,Methadone,Meth/Amphetamine,Tramadol,Hydromorphone,Morphine (not heroin),Other,Unnamed: 25,Unnamed: 26
0,1,1/1/19,Male,White,58,Residence,Bridgeport,Fairfield,CT,6604,...,0,0,0,0,0,0,0,0,NaN,NaN
1,2,1/1/19,Male,Black or African American,22,"Other, Residential Institution",Norwalk,Fairfield,CT,6854,...,0,1,0,0,0,0,0,1,NaN,NaN
2,3,1/1/19,Male,"Hispanic, White",60,Residence,Waterbury,New Haven,CT,6708,...,0,0,0,0,0,1,0,0,NaN,NaN
3,4,1/1/19,Male,"Hispanic, White",33,Residence,Meriden,New Haven,CT,6450,...,0,0,0,0,0,0,0,0,NaN,NaN
4,5,1/2/19,Male,White,24,Residence,Glastonbury,Hartford,CT,6033,...,0,1,0,0,0,0,0,0,NaN,NaN

In [4]:
df.to_sql("ct_opioiddata_final", conn, if_exists="replace", index=False)

7681

In [6]:
#query to make sure we imported and created it properly
query = "SELECT * FROM ct_opioiddata_final LIMIT 5;"
result = pd.read_sql(query, conn)
print(result)

   IncidentID DateReported   Sex                       Race  Age  \
0           1       1/1/19  Male                      White   58
1           2       1/1/19  Male  Black or African American   22
2           3       1/1/19  Male            Hispanic, White   60
3           4       1/1/19  Male            Hispanic, White   33
4           5       1/2/19  Male                      White   24

                      InjuryPlace   InjuryCity InjuryCounty InjuryState  \
0                       Residence   Bridgeport    Fairfield          CT
1  Other, Residential Institution      Norwalk    Fairfield          CT
2                       Residence    Waterbury    New Haven          CT
3                       Residence      Meriden    New Haven          CT
4                       Residence  Glastonbury     Hartford          CT

   InjuryZip  ...  Hydrocodone  Benzodiazepines  Methadone  Meth/Amphetamine  \
0       6604  ...            0                0          0                 0
1       6854  ...            0                1          0                 0
2       6708  ...            0                0          0                 0
3       6450  ...            0                0          0                 0
4       6033  ...            0                1          0                 0

   Tramadol  Hydromorphone  Morphine (not heroin)  Other  Unnamed: 25  \
0         0              0                      0      0         None
1         0              0                      0      1         None
2         0              1                      0      0         None
3         0              0                      0      0         None
4         0              0                      0      0         None

   Unnamed: 26
0         None
1         None
2         None
3         None
4         None

[5 rows x 27 columns]